# Generated by Django 3.0.3 on 2020-02-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=600)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600)),
                ('notes', models.CharField(max_length=600)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProjectAction.Project')),
            ],
        ),
    ]
