# Generated by Django 3.0.3 on 2020-02-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProjectAction', '0003_auto_20200229_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
